format_version: 9
environments:
  testing:
    environment_variables:
      DEPLOYMENT: testing
pipelines:
  mhce:
    group: mygroup
    materials:
      mygit:
        git: https://gitlab.com/qnib-metahub/community-edition.git
    stages:
      - build:
          jobs:
            build:
              tasks:
               - exec:
                   command: echo
